### ISSUE TITLE
Applying recommendations immediately leads to OOMKilled on startup

### ISSUE THREAD

**Issue by adampetrovic** [robusta-dev/krr#110]
**Describe the bug**
I am new to right-sizing k8s clusters and thought I'd give krr a try.

I've used all the default settings (history and buffer) and krr has suggested significant changes across many of my pods.

Upon applying them across two of my example pods, I immediately get OOMKilled errors.

**To Reproduce**
N/A

**Expected behavior**
A pod's expected memory footprint to be taken into consideration and not have its memory limit set so low that it can't start.

**Screenshots**
<img width="450" alt="CleanShot 2023-07-18 at 13 46 26@2x" src="https://github.com/robusta-dev/krr/assets/88030/f46e2ba4-133d-4add-9530-8f7dc279a60f">

<img width="1570" alt="CleanShot 2023-07-18 at 13 46 40@2x" src="https://github.com/robusta-dev/krr/assets/88030/ff78c89b-bf2b-4873-8441-4de78c9c552a">

<img width="1238" alt="CleanShot 2023-07-18 at 13 47 45@2x" src="https://github.com/robusta-dev/krr/assets/88030/692584b7-1f05-4dca-998d-de889f5eee54">

As can be seen in the above screenshot, HomeAssistant exceeds 1GB of memory use on a number of occasions in the past week, but krr suggests 516Mi as its memory limit.

Any tips on how to make this more useful?

**Comment by LeaveMyYard** [comment]
Hey, @adampetrovic!

Thank you very much for reporting and helping the project. 

Could you send me the exact promql query that was used to build the second image (I assume it is grafana)? KRR uses the history data using `container_memory_working_set_bytes` metric for 2 weeks of data and adding a buffer to it, so your behaviour is unexpected, as from your graph the recommendation should have been around 1.6Gi

Also, could you please tell what version are you using? And if you were using the source code - what commit tag.

**Comment by adampetrovic** [comment]
Yep, here it is:
```
sum(container_memory_working_set_bytes{job="kubelet", metrics_path="/metrics/cadvisor", cluster="$cluster", namespace="$namespace", pod="$pod", container!="", image!=""}) by (container)
```

**Comment by LeaveMyYard** [comment]
@adampetrovic can you please check if the graph in grafana has "Stack" visualisation setting turned on (on the graph that you provided)?

**Comment by adampetrovic** [comment]
Yes, stack is enabled. If you look closely at some of those spikes they are around the 1GB mark (when the total is 1.4GB)

**Comment by LeaveMyYard** [comment]
@adampetrovic can you try using calculation_improvement branch and tell me what results do you get from them?

Also, it would be really useful if you'll provide separate plots for each container

**Comment by adampetrovic** [comment]
Things are much better now that I am using the latest master (which seems to have had that branch merged in).

I'll close it off!
