### ISSUE TITLE
New installation method: asdf

### ISSUE THREAD

**Issue by djfinnoy** [robusta-dev/krr#137]
**Is your feature request related to a problem? Please describe.**
Linux users have to install `krr` manually via python or with homebrew, ..sad times.

**Describe the solution you'd like**
`asdf` is the ultimate package manager for CLI tools (it's great, you should all be using it), I would love to see an official `krr` plugin for `asdf`

https://asdf-vm.com/

**Describe alternatives you've considered**
If `krr` can be published as a simple binary, that would also be nice.

**Additional context**

**Comment by LeaveMyYard** [comment]
Actually you can find a standalone binary in assets for each release (do not require python installation)
https://github.com/robusta-dev/krr/releases

As for `asdf` - we will consider it in the future

**Comment by djfinnoy** [comment]
Thank you :)
