### ISSUE TITLE
[FEATURE] Add VictoriaMetrics support

### ISSUE THREAD

**Issue by denisgolius** [robusta-dev/krr#14]
Could you please add [VictoriaMetrics](https://victoriametrics.com/products/open-source/) support? VictoriaMetrics support PromQL as well as Graphite queries so it should work.

**Comment by v2nek** [comment]
With VM on this branch and on main branch results look like this:
![image](https://user-images.githubusercontent.com/555475/233695406-785b04f9-ca11-4ed7-ae13-f8ce00f9ff86.png)

**Comment by aantn** [comment]
Do you have any idea where it's breaking down? Is it not finding VM or finding some other Prometheus in your cluster? Or is it finding VM and querying it, but the metric it's fetching doesn't exist.

If possible, please share logs from verbose mode.

**Comment by taivo123** [comment]
> @denisgolius does the `fix-CPU-metric` branch work for you? You might still need to explicitly point krr at VictoriaMetrics (just pretend it's Prometheus)

worked for our VictoriaMetrics, thanks :)

**Comment by LeaveMyYard** [comment]
Closing this issue, as the feature is implemented
