### ISSUE TITLE
1.6.0 TypeError, 1.5.3 works

### ISSUE THREAD

**Issue by EvertonSA** [robusta-dev/krr#147]
**Describe the bug**
After upgrading from 1.5.3 to 1.6.0, we get the following error:

│ ❱ 201 │   │   related_pods = [pod["metric"]["pod"] for pod in related_pods_result]
TypeError: string indices must be integers, not 'str'

After checking v1.5.3 again, it works as expected.

**To Reproduce**
Unfortunately, I'm not sure how to reproduce other than running python .\krr.py simple on a working prometheus setup. 

**Expected behavior**
I would expect to have same behavior as 1.5.3

**Screenshots**
![image](https://github.com/robusta-dev/krr/assets/30481051/53df9bd4-4999-48b6-a110-f9ee9685e1b2)

**Comment by EvertonSA** [comment]
i'm willing to provide further data, or test release candidate fixes if needed

**Comment by LeaveMyYard** [comment]
Hey, @EvertonSA!

Your error is a bit odd - `custom_query` returns something unexpected
Can you add 
```python
raise Exception(related_pods_result)
```
before 
```python
related_pods = [pod["metric"]["pod"] for pod in related_pods_result]
```
in robusta_krr/core/integrations/prometheus/metrics_service/prometheus_metrics_service.py, run it and then show me the resulted exception, to help me to understand what's going on? Thank you in advance

**Comment by LeaveMyYard** [comment]
Also this might be somehow related to #127

**Comment by LeaveMyYard** [comment]
@EvertonSA Can you try #150 ?

**Comment by EvertonSA** [comment]
I confirm #150 150 works !
