### ISSUE TITLE
Unit alignment

### ISSUE THREAD

**Issue by roe-pinhas-rs** [robusta-dev/krr#15]
The unit measured is not aligned, which makes the compartment difficult. For example in memory usage:
k to M  
2097152k -> 498M
Mi to M
128Mi -> 995M

**Comment by LeaveMyYard** [comment]
Hey, @roe-pinhas-rs!

Fare point. I will come up with the enchanced solution and update you here

**Comment by LeaveMyYard** [comment]
The fix was implemented in some point, v1.2 contains it. Now we show memory only in decimal format (M, G etc)
