### ISSUE TITLE
Flag for krr to filter by resource kind list seems broken in v1.6.0

### ISSUE THREAD

**Issue by samavasi** [robusta-dev/krr#161]
**Describe the bug**
Flag for krr to filter by resource kind list seems broken in v1.6.0

**To Reproduce**
1. krr simple -r Deployment

**Expected behavior**
Filter will be applied when querying target objects. Currently getting error:

2 validation errors for Config
resources -> 0
  unexpected value; permitted: 'Deployment', 'DaemonSet', 'StatefulSet', 'Job', 'Rollout' (type=value_error.const; given=deployment; permitted=('Deployment', 'DaemonSet', 'StatefulSet', 'Job', 'Rollout'))
resources
  unhashable type: 'list' (type=type_error)

**Additional context**
Also if passing multiple resource kinds e.g.  -r Deployment,Job expected filter to work against the sublist of resources. currently omitting the filter for resources seems to be the only working solution (but I want to skip all Job owned pods)

**Comment by mozai** [comment]
When this is repaired, would also like in the help text how to list multiple resources:  do I use `-r thing1 -r thing2` or `-r "thing1 thing2"` or `-r thing1,thing2` ?

**Comment by shoulda** [comment]
> **Describe the bug** Flag for krr to filter by resource kind list seems broken in v1.6.0
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. krr simple -r Deployment
> 
> **Expected behavior** Filter will be applied when querying target objects. Currently getting error:
> 
> 2 validation errors for Config resources -> 0 unexpected value; permitted: 'Deployment', 'DaemonSet', 'StatefulSet', 'Job', 'Rollout' (type=value_error.const; given=deployment; permitted=('Deployment', 'DaemonSet', 'StatefulSet', 'Job', 'Rollout')) resources unhashable type: 'list' (type=type_error)
> 
> **Additional context** Also if passing multiple resource kinds e.g. -r Deployment,Job expected filter to work against the sublist of resources. currently omitting the filter for resources seems to be the only working solution (but I want to skip all Job owned pods)

Hi, I also met the issue, should you resolved it?

**Comment by LeaveMyYard** [comment]
Fixed in e575f240eef127bde5826c0c1987374caf7f80e3
