### ISSUE TITLE
Feature request : export to a csv file

### ISSUE THREAD

**Issue by hafx** [robusta-dev/krr#163]
Hello, 

Maybe a feature request. 

I'm searching a solution to export the result to a csv file. 
I feel more conformable to use excel than the output bash. (with excel better global view, can sort cells by name, by values, ...) 

I seen that it is possible to generate a json or yaml, but nothing about csv. 

Is it possible to convert a json or yaml easily to csv? 

Any idea, thanks for your help.

**Comment by aantn** [comment]
Hi @hafx,
No CSV support yet, but PRs are welcome! To get an idea of what is involved in adding it, take a look at the other exporters (formatters) here: https://github.com/robusta-dev/krr/tree/main/robusta_krr/formatters

**Comment by hafx** [comment]
Hi @aantn, 
Yes, thanks for the link about the formatters. 
I'm going to make a PR.

**Comment by aantn** [comment]
Wonderful,  looking forward to it. If you have questions feel free to ask
in the #contributors channel on Slack.

**Comment by aantn** [comment]
No one else is working on it as far as I know. Go for it and can't wait for that PR!

**Comment by whaakman** [comment]
I put something in: https://github.com/robusta-dev/krr/pull/227
