### ISSUE TITLE
Support Prometheus versions before 2.26

### ISSUE THREAD

**Issue by njyrbecker** [robusta-dev/krr#164]
**Describe the bug**
Installed krr v1.6.0 on my macbook via brew, pointed krr at my cluster, it crashed on running with the following error message:
(backtrace excluded, can add it if it would be helpful)
```
PrometheusApiClientException: HTTP Status Code 400 (b'{"status":"error","errorType":"bad_data","error":"invalid parameter \'query\': parse error at line 2,
char 32: unknown function with name \\"last_over_time\\""}')
```

**Software versions**
Prometheus v2.12.0
kube-state-metrics v2.4.1
krr v1.6.0

run with:
```
krr simple -n staging -p http://url.to.prometheus
```

**Expected behavior**
Expecting the krr report on resource limit recommendations

**Additional context**
I checked and it's clear prometheus and kube-state-metrics are somewhat backrev.   The docs for krr don't indicate specific version compatibility.   I  can look into upgrading the software, but if there are known version incompatibilities or older versions of krr that might work with the older versions, that would be really helpful before I start digging without knowing where I'm headed.  Thanks!

**Comment by aantn** [comment]
Hey, we don't have any official guide on version compatibility right now. But if you do that research, please open a PR and contribute your findings! 

We test KRR regularly on the version of kube-prometheus-stack bundled with [Robusta OSS](https://github.com/robusta-dev/robusta) but we don't have a full test matrix beyond that. (Yet.)

Any contribution to docs or a testing system would be great.

**Comment by aantn** [comment]
Thanks @dgdevops, nice catch.

I've updating the README and am updating the issue's title.

Just a heads up - we're not prioritizing support for earlier Prometheus versions at the moment. But - as always - PRs are welcome.
