### ISSUE TITLE
KRR fails to connect to Thanos for recommendations on OpenShift

### ISSUE THREAD

**Issue by davecore82** [robusta-dev/krr#170]
**Describe the bug**
Encountering an issue with KRR for obtaining recommendations on OpenShift 4.12.34. The problem seems to arise when the tool attempts to connect to Thanos, as it appears to fail authentication in this process.

**To Reproduce**
1. Install KRR v1.6.0, run on OpenShift 4.12.34 cluster (vanille IPI install on AWS)
2. Run with `krr simple --verbose`
3. Observe the error:

```
on 0: [INFO] Connecting to Thanos for openshift-ingress/api-dcoronel-vmware-<rest of name removed>:6443/system:admin cluster
on 0: [DEBUG] Trying to find service with label selector app.kubernetes.io/component=query,app.kubernetes.io/name=thanos
on 0: [DEBUG] Trying to find ingress with label selector app.kubernetes.io/component=query,app.kubernetes.io/name=thanos
on 0: [DEBUG] Trying to find service with label selector app.kubernetes.io/name=thanos-query
on 0: [DEBUG] Found service with label selector app.kubernetes.io/name=thanos-query
on 0: [INFO] Using Thanos at https://api.dcoronel.vmware.<rest of hostname removed>:6443/api/v1/namespaces/openshift-monitoring/services/thanos-querier:9091/proxy for cluster openshift-ingress/api-dcoronel-vmware-<rest of name removed>:6443/system:admin
on 0: [DEBUG] Thanos not found: Couldn't connect to Thanos found under https://api.dcoronel.vmware.<rest of hostname removed>:6443/api/v1/namespaces/openshift-monitoring/services/thanos-querier:9091/proxy
      Caused by PrometheusNotFound: Couldn't connect to Prometheus found under https://api.dcoronel.vmware.<rest of hostname removed>:6443/api/v1/namespaces/openshift-monitoring/services/thanos-querier:9091/proxy
      Caused by HTTPError: 403 Client Error: Forbidden for url: https://api.dcoronel.vmware.<rest of hostname removed>:6443/api/v1/namespaces/openshift-monitoring/services/thanos-querier:9091/proxy/api/v1/query))
on 0: [ERROR] No Prometheus or metrics service found
```

**Expected behavior**
Expected KRR to successfully provide recommendations(ie. for setting CPU requests and limits)

**Are you interested in contributing a fix for this?**
no

**Additional context**
I suspect that the problem lies in the tool's inability to authenticate to Thanos, leading to the failure in obtaining recommendations.

**Comment by aantn** [comment]
Hey, thanks for reporting. Is the issue one of authentication then, or that the /proxy endpoint doesn't exist altogether? (If auth, we have the `--prometheus-auth-header` flag - see examples in README.)

**Comment by mrmt32** [comment]
This worked for me on openshift:

```
krr simple --prometheus-url "https://$(oc get route -n openshift-monitoring prometheus-k8s -o jsonpath='{.status.ingress[0].host}')"  --prometheus-auth-header "Bearer $(oc whoami -t)" 
 ```
 
(i.e. explicitly pointing it at the external thanos route and passing it a valid kubernetes bearer token)

**Comment by odorT** [comment]
@mrmt32's solution just works, thanks
