### ISSUE TITLE
Add long term storage support (Thanos)

### ISSUE THREAD

**Issue by farodin91** [robusta-dev/krr#18]
We are currently just storing 24h in our local prometheus and using for anything longer thanos. 

It would cool to use thanos by filtering results based on a custom label set.

**Comment by CGPrakashW** [comment]
Hi, not sure whether this will work for you but I've been able to run krr against thanos using the `-p` flag to set the prometheus-url to the thanos query component in Thanos.

**Comment by farodin91** [comment]
My thanos contains data from multiple cluster so it would be help to filter by a label such as cluster.

**Comment by CGPrakashW** [comment]
Just a small update, I've been able to query thanos for metrics in a multi-cluster configuration by querying a prom label proxy instance sitting in front of thanos query: https://github.com/prometheus-community/prom-label-proxy

**Comment by DjoleLepi** [comment]
@CGPrakashW 

> Just a small update, I've been able to query thanos for metrics in a multi-cluster configuration by querying a prom label proxy instance sitting in front of thanos query: https://github.com/prometheus-community/prom-label-proxy

Could you provide the query you used for this?
I tried `-p prom-label-proxy.example.com/api/v1/query?cluster="cluster-name"` but it doesn't seem to provide the metrics

**Comment by CGPrakashW** [comment]
> @CGPrakashW
> 
> > Just a small update, I've been able to query thanos for metrics in a multi-cluster configuration by querying a prom label proxy instance sitting in front of thanos query: https://github.com/prometheus-community/prom-label-proxy
> 
> Could you provide the query you used for this? I tried `-p prom-label-proxy.example.com/api/v1/query?cluster="cluster-name"` but it doesn't seem to provide the metrics

Sure, what worked for me was just whatever endpoint is exposed for prom-label-proxy, i.e in your example it would just be `https://prom-label-proxy.example.com`. 

Then within prom-label-proxy the label is applied to the query before being passed onto thanos, as described in their readme.

**Comment by DjoleLepi** [comment]
@CGPrakashW 

Thank you very much! I have completely missed that part in the readme. https://github.com/robusta-dev/krr#scanning-with-a-centralized-prometheus

I was also able to use these parameter `--prometheus-label cluster -l cluster-name` with Thanos (no need for prom-label-proxy).

It seems like this issue can be closed? @LeaveMyYard

**Comment by aantn** [comment]
@DjoleLepi is there anything we can update in the readme or --help to make it more obvious?

No good having the feature if people aren't finding it!

**Comment by LeaveMyYard** [comment]
@DjoleLepi I think just to add `Thanos` and `VictoriaMetrics` to readme should be enough

I'm closing this issue, as we already support Thanos
