### ISSUE TITLE
Log to stderr

### ISSUE THREAD

**Issue by Dentrax** [robusta-dev/krr#19]
That's because `-v` flag omits some logs to _stdout_, which appends the verbose-related logs in the generated-JSON file. So the following steps does not work:

```bash
$ python krr.py simple -v -f json > result.json
$ cat result.json | jq
parse error: Invalid numeric literal at line 3, column 7
```

In the expected behaviour, krr should log to stderr and JSON output to stdout. Wdyt?

**Comment by LeaveMyYard** [comment]
Hey, @Dentrax!

Thanks for pointing it out. I think it is just an error in the readme and it should be `-q` and not `-v` (`-q` stands for quiet and `-v` for verbose)
```bash
python krr.py simple -q -f json > result.json
```

In terms of logging to stderr I am not sure if this is the logical thing to do, as logs are not really errors. In any case, could you please tell, if using `-q` flag will do the job for you?

**Comment by LeaveMyYard** [comment]
Just checked out and it is correct in the readme:

```bash
python krr.py simple -q -f json > result.json
```

**Comment by Dentrax** [comment]
You are right, I could pass `-q` here. But the point I'm trying to express is _logging to stderr_.

> In terms of logging to stderr I am not sure if this is the logical thing to do, as logs are not really errors.

I usually see `--logtostderr` flag across in the [big projects](https://cs.github.com/?scopeName=All+repos&scope=&q=%22--logtostderr%22). It's also kubernetes-sigs projects standard.

So I don't have to pass `-q` flag every time when I redirect the output to file. In current implementation, how can I export both of verbose logs and the _given_ output type in the same time? (It's mutually exclusive design)

Feel free to close if you don't like the idea, it was just a thought.

**Comment by LeaveMyYard** [comment]
I actually like the idea of `--logtostderr`

I will try to implement it today as it should be simple and update you

**Comment by LeaveMyYard** [comment]
@Dentrax 

Take a look into #22. Feel free to re-open the issue if you think there is something more to be added.
