### ISSUE TITLE
Prometheus detection : remove prometheus-msteams ?

### ISSUE THREAD

**Issue by MrLuje** [robusta-dev/krr#193]
**Describe the bug**
I'm using a rancher-based cluster, so integrated prometheus stack and also have installed https://github.com/prometheus-msteams/prometheus-msteams
Running KRR without arguments picks `prometheus-msteams` by default instead of prometheus.
The thing is `prometheus-msteams` is a webhook forwarder for ms-teams so I think it shouldn't even belong to the list
```
"app=kube-prometheus-stack-prometheus"
"app=prometheus,component=server"
"app=prometheus-server"
"app=prometheus-operator-prometheus"
"app=prometheus-msteams"
"app=rancher-monitoring-prometheus"
"app=prometheus-prometheus"
```

**To Reproduce**
1. krr simple -n system-rci
```log
[INFO] Using clusters: ['k8s-dev']
on 0: [INFO] Listing scannable objects in k8s-dev
on 0: [INFO] Connecting to Prometheus for k8s-dev cluster
on 0: [INFO] Using Prometheus at https://xxxxx/monitoring/services/prometheus-msteams:2000/proxy for cluster k8s-dev
on 0: [INFO] Connecting to Victoria for k8s-dev cluster
on 0: [INFO] Connecting to Thanos for k8s-dev cluster
on 0: [ERROR] No Prometheus or metrics service found
```
2. whereas `krr simple -p https://xxxxx/cattle-monitoring-system/services/http:rancher-monitoring-prometheus:9090/proxy -n` works properly -n system-rci

**Expected behavior**
KRR shouldn't use non-eligible apps as metrics provider

**Are you interested in contributing a fix for this?**
If we are talking about removing this label from the list, yes :)

**Desktop (please complete the following information):**
 - Windows 11 / WSL2
 - k8s : v1.22.10
 - krr : v1.6.0

**Comment by LeaveMyYard** [comment]
@arikalon1 WDYT? This also applies to the runner, as I understand

As an alternative we can try to connect to everything that fits lables, not only the first one

**Comment by arikalon1** [comment]
@pablos44 

@MrLuje is correct, `prometheus-msteams` is not a metrics provider
We should remove it from the auto detection list

@MrLuje as a work around, you can specify the prometheus url manually
