### ISSUE TITLE
KRR - ADD deploymentconfig Object

### ISSUE THREAD

**Issue by faCalegari** [robusta-dev/krr#199]
I need to know if is posible evaluate DeploymentConfig objetcs.

Thanks

**Comment by aantn** [comment]
We're working on this now.

Would love to jump on a call with anyone who is interested and discuss better OpenShift suport in general. If relevant, please comment below or message me on [our Slack community.](https://bit.ly/robusta-slack)

**Comment by LeaveMyYard** [comment]
@faCalegari 
We have added DeploymentConfigs (as well as CronJobs) in this PR: https://github.com/robusta-dev/krr/pull/228
