### ISSUE TITLE
Brainstorming: krr-operator

### ISSUE THREAD

**Issue by Dentrax** [robusta-dev/krr#20]
I was thinking about to create a Kubernetes operator that reads the output of _krr_ and apply the recommended values to corresponding cluster. However, I don't feel comfortable while writing Python and was thinking to create an operator in Go that calls _krr_ under the hood to grab recommended values and apply using the `client-go` API. So I thought we could officially provide an operator.

Some design ideas:

* Introduce the operator in the separate repo vs use this one as a monorepo
* Create a container image for krr-operator
* It's long running standalone single Pod that check and apply recommended values in scheduled manner
	* leader-election may needed for H/A (may not needed in the first phase)
	* some Prometheus metrics for monitoring stuff (may not needed in the first phase)
* A reconciler: subscribe to [informers](https://pkg.go.dev/k8s.io/client-go/informers) and apply recommended values immediately (this is required because once we edit the CPU/MEM values, a new deployment may override it, so might think of re-applying. may not needed in the first phase)

It'd be perfect opportunity to introduce an operator for this brilliant tool. Wdyt?

**Comment by LeaveMyYard** [comment]
Hey, @Dentrax!

I think we have future plans for doing the automatic apply, so this is a really good proposition.
If you wish to help the project, you can write the operator on anything you like and we can follow with the support of what you will come up with.

I personally hasn't worked with Go yet, but it should be a good reason to try it out 😄

**Comment by aantn** [comment]
If anyone wants to look into this further at some point, another approach could be a custom formatter that outputs a mutating Kvyrno policy, or something along those lines.
