### ISSUE TITLE
VPA in recommendation mode

### ISSUE THREAD

**Issue by Vahan90** [robusta-dev/krr#206]
**Is your feature request related to a problem? Please describe.**
Similar to the complaint in #169, It would make `krr` a much more complete tool if it works with `HPA`'s / `ScaledObject`'s

**Describe the solution you'd like**
Maybe a new strategy that could work out with setting `VPA`'s in recommendation mode, use the algorithm with the metrics it would produce, and use it to generate the recommendations.

**Describe alternatives you've considered**
-

**Are you interested in contributing a PR for this?**
Yes

**Additional context**

**Comment by Vahan90** [comment]
Found out the answer to my question. 

Not feasible. Will look for another way.

**Comment by aantn** [comment]
Hey, sorry on the delayed reply. Not currently possible, as you pointed out.

But what is the main thing that is missing? Is it support for HPA/ScaledObjects? If we had that, would the VPA integration still be necessary?

**Comment by aantn** [comment]
What metric are you using for scaling your HPAs? Is it CPU utilization or something else?
