### ISSUE TITLE
skips kube-system namespace despite saying it scans all namespaces by default

### ISSUE THREAD

**Issue by fenio** [robusta-dev/krr#208]
**Describe the bug**

krr says in help that by default it runs on all namespaces:

```
[☸ lab:database] [⏱ 2s]
❯ ~ krr simple --help | grep namespace
│ --namespace          -n      TEXT  List of namespaces to run on. By default, will run on all namespaces. [default: None]
```

This is not true. Seems it by default skip kube-system namespace.

**To Reproduce**
Run `krr simple` and then run `krr simple --namespace kube-system`.
Second invocation will list resources that were absent in first invocation.

**Expected behavior**
Either help should be updated to state that kube-system is excluded by default or default behaviour should be changed to include kube-system namespace.

**Comment by aantn** [comment]
Yep, you are right. Would you be interested in opening a PR to fix it?

**Comment by fenio** [comment]
I can provide PR but the question is which behaviour would you like to be default.
Should I just update help to make it clear that kube-system is skipped or should I remove part of the code which in fact intentionally skips it?
```
                # NOTE: By default we will filter out kube-system namespace
                if settings.namespaces == "*" and object.namespace == "kube-system":
                    continue
```
After all it's your program ;)

**Comment by aantn** [comment]
Please update the help. Many of our users are running on managed Kubernetes providers and have workloads in kube-system that they do not control. So we would like to keep excluding it by default.
