### ISSUE TITLE
No recommendations are returned by Krr 1.7.0 when --quiet and --formatter json are used together

### ISSUE THREAD

**Issue by agabrys** [robusta-dev/krr#214]
**Describe the bug**

When the `--quiet` and `--formatter json` parameters are used together, no recommendations are returned.

**To Reproduce**

1. Execute `krr simple --quiet --kubeconfig <kubeconfig> --context <context> --namespace <namespace> --formatter json` ← no data
2. Execute `krr simple --kubeconfig <kubeconfig> --context <context> --namespace <namespace> --formatter json` ← logs + data

**Expected behavior**

When the `--quiet` and `--formatter json` parameters are used together, recommendations data in JSON format should be printed to the output.

**Are you interested in contributing a fix for this?**

Yes. I can help with testing.

**Desktop:**
 - OS: Microsoft Windows NT 10.0.22631.0
 - krr: v1.7.0

**Comment by MaximBogun** [comment]
I have the similar issue on **MacOs** env, just no output.
