### ISSUE TITLE
Freezes during information gathering

### ISSUE THREAD

**Issue by maMykola** [robusta-dev/krr#245]
**Describe the bug**
For some namespaces the krr freezes on gathering INFO data.

**To Reproduce**
```shell
python krr.py simple --allow-hpa -n external-secrets
```

**Expected behavior**
The command should be executed successfully.

**Screenshots**
<img width="1653" alt="image" src="https://github.com/robusta-dev/krr/assets/3263273/653d8d90-ce21-43eb-89b2-ffc5af015480">

**Are you interested in contributing a fix for this?**
Yes.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04, macOS Sonoma 14.4
 - Python 3.11.8

**Additional context**
The issue arise immediately after 1.7.1 release and possibly caused by this commit https://github.com/robusta-dev/krr/commit/4c8e727205221f4d38a638b3ed51dea568b26309

**Comment by aantn** [comment]
Thanks for reporting. I think you're right on the cause and we're working on a fix.

**Comment by LeaveMyYard** [comment]
@maMykola Could you check if #249 works for you?

**Comment by maMykola** [comment]
> @maMykola Could you check if #249 works for you?

yes, it works now
