### ISSUE TITLE
Ability to set custom Prometheus data source for `remote_write` users

### ISSUE THREAD

**Issue by Dentrax** [robusta-dev/krr#25]
This feature is desirable for users who use the Prometheus's [remote_write](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_write) feature. We push the metrics to remote Victoria Metric agents so all Prometheus (kube-prometheus) instances in the clusters has 4 hours of retention. We also append a `_cluster=my-cluster-name` label for each metric to identify where the metric is coming from.

```bash
$ kubectl get secrets prometheus-prometheus-operator-kube-p-prometheus -o json | jq '.data."prometheus.yaml.gz"' -r | base64 -d | gunzip | yq e '.remote_write' -

- url: http://my-remote-vmagent/api/v1/write
```

I'd be nice to set manually Prometheus instance address with some custom label selectors (to ensure the corresponding cluster we are querying is correct). Any thoughts?

**Comment by LeaveMyYard** [comment]
I think there is already someone asking for Victoria Metric support in #14. Already looks like a requested feature.
@aantn What do you think?

**Comment by LeaveMyYard** [comment]
Centralized VictoriaMetrics is implemented, so you can connect to it directly
