### ISSUE TITLE
Prometheus returned no PercentileCPULoader metrics with the simple strategy

### ISSUE THREAD

**Issue by DzeCin** [robusta-dev/krr#280]
**Describe the bug**
When running krr version 1.8.3 (the windows binary) with the simple stratey, I can get the memory recommendations but not the CPU one.
I get those logs "Prometheus returned no PercentileCPULoader metrics with the simple strategy".
On the version 1.4.1, the cpu recommendations (and the memory one) work.

I have all the requested metrics.

**To Reproduce**
1. Open powershell
2. Port forward prometheus svc : kubectl port-forward -n monitoring svc/prometheus-server 80:80
3. Run .\krr.exe simple -p http://localhost:80 --memory_buffer_percentage=5
4. Logs such as "Prometheus returned no PercentileCPULoader metrics for Deployment" appear
5. Get this table:
<img width="942" alt="image" src="https://github.com/robusta-dev/krr/assets/56233944/1414aa53-8c78-4fa0-8f74-7ad66c7d40db">

**Expected behavior**
I expect that the CPU requests and limits are caclulated

**Screenshots**
<img width="942" alt="image" src="https://github.com/robusta-dev/krr/assets/56233944/ae20f5f6-529b-45e8-a510-8b6430bd34e1">

**Are you interested in contributing a fix for this?**
Yes

**Desktop (please complete the following information):**
 - OS: Windows Server 2022 Datacenter Azure Edition
 - KRR Version 1.8.3

**Additional context**
It works fine with KRR 1.4.1, even though the memory recommendation given are not the same as the version 1.8.3.

**Comment by DzeCin** [comment]
Hello,
Yes looks better now thanks

**Comment by aantn** [comment]
Happy to hear it, thanks for the update.
