### ISSUE TITLE
v1.9.0 not released to brew due to failed github action

### ISSUE THREAD

**Issue by curantes** [robusta-dev/krr#283]
**Describe the bug**
the github action to build and release v1.9.0 failed so no upgrade is available in brew

https://github.com/robusta-dev/krr/actions/runs/9190299607

**Comment by arikalon1** [comment]
Thanks @curantes 

@Avi-Robusta can you please check?

**Comment by aantn** [comment]
Just to update everyone, we are working on a fix and expect to release it in the upcoming week or so. Thank you for the patience!

**Comment by aantn** [comment]
Hey all, this should be fixed. If you encounter any more issues please report them!
