### ISSUE TITLE
Binaries missing for 1.9.0

### ISSUE THREAD

**Issue by GoldennDragonn** [robusta-dev/krr#285]
Latest 1.9.0 release page is missing the binaries. The 1.8.3 release page does provides them.

**Comment by aantn** [comment]
Hey, thank you for reporting! This is due to a problem with the github actions and we will have a fix in the upcoming week.

**Comment by GoldennDragonn** [comment]
Thank you for taking care of this issue.

**Comment by aantn** [comment]
With pleasure! And please keep reporting issues you find!
