### ISSUE TITLE
Add flags for controlling the memory buffer applied over the maximum value recorded

### ISSUE THREAD

**Issue by george-c29** [robusta-dev/krr#294]
**Is your feature request related to a problem? Please describe.**
For larger periods of time that the report is generated for (e.g. last 3 months), if the spikes of the app are rare but significant, the  99th percentile value for memory is naturally lower (since the spikes account for less than 1% of the usage), resulting in memory suggestions that will cause the pod to fail due to an OOMKilled event. In order to avoid this, we could manipulate the memory buffer applied over the maximum value recorded.

**Describe the solution you'd like**
A dedicated flag or set of flags for controlling the default 15% memory buffer applied to the calculation of the memory request&limits, similar to how you can currently tweak the min cpu/mem:
_For memory, we take the maximum value over the past week and add a 15% buffer._

_Most helpful flags:
--cpu-min Sets the minimum recommended cpu value in millicores
--mem-min Sets the minimum recommended memory value in MB
--history_duration The duration of the Prometheus history data to use (in hours)_

such as:
--mem-buffer Sets the percentage of memory that is added as a buffer over the maximum value from the last 7 days (default period)

**Describe alternatives you've considered**
At the moment there are no alternatives to tackle this specific scenario

**Are you interested in contributing a PR for this?**
Yes

**Comment by aantn** [comment]
Hi, thanks for opening. This shouldn't happen because for memory we're recommending values based on the maximum historical value, not the p99. Is it possible that the app really just had lower values (including the max) in the historical period? If so, you can solve this by increasing the buffer we add to the maximum with the existing flag.

We also have an experimental flag that looks at OOMs and takes them into account for the recommendations. If there were OOMs in the historical period that could be useful for you too.

**Comment by george-c29** [comment]
Hi @aantn, thanks for the clarifying comments! My mistake, the krr simple --help command described more flags than I was aware of:

_--memory-buffer-percentage,--memory_buffer_percentage        TEXT  The percentage of added buffer to the peak memory usage for memory recommendation. [default: 15]_

And specifically this is the one I needed. Thank you!

**Comment by george-c29** [comment]
@aantn what is the experimental flag you were mentioning and in which version could I start using it?

**Comment by aantn** [comment]
`--use-oomkill-data` and `--oom-memory-buffer-percentage` in version 1.9.0 and above.
They are disabled by default as we have not yet gotten enough user feedback on them. So if you test please share your inputs on:

1. Did they worked as expected?
2. Did running KRR with those flags make KRR run more slowly? (How long did it take for KRR to do a full scan of your cluster with and without those flags?)
