### ISSUE TITLE
Algorithm CPU percentil  in documentation correct?

### ISSUE THREAD

**Issue by mgfnv9** [robusta-dev/krr#297]
This is not bug.

In site https://github.com/robusta-dev/krr?tab=readme-ov-file#algorithm you type 

`For CPU, we set a request at the 99th percentile, `

but then I running krr by default I see 95 percentil

`CPU request: 95.0% percentile, limit: unset
Memory request: max + 15.0%, limit: max + 15.0%
`

I don't understand CPU 95 or CPU 99 percentil correct for use?

krr:1.10.0

**Comment by aantn** [comment]
It is a bug in the docs!

95th percentile is correct on the latest version.

**Comment by aantn** [comment]
It is a bug in the docs!

95th percentile is correct on the latest version.
