### ISSUE TITLE
error when context not set

### ISSUE THREAD

**Issue by marafa-sugarcrm** [robusta-dev/krr#30]
**Describe the bug**

i work with  more than a couple of clusters. to avoid confusing myself i do not set contexts forcing myself to do that for each kubectl command i write.

which means i get this error:

`kubernetes.config.config_exception.ConfigException: Invalid kube-config file. Expected object with name  in ${HOME}/.kube/config/contexts list`

i had to use kubectx to set context for krr to work

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by LeaveMyYard** [comment]
Hey, @marafa-sugarcrm 

Could you please explain a little bit more about why `-c` setting do not work for you?
I think the error means that the cluster name that you provided does not exist in `~/.kube/config`. Could it be the typo in your command?

**Comment by LeaveMyYard** [comment]
I think the issue might be related to kubectx, as you mentioned that you are using it.
In any case this is a bug and I will fix it in a future.

**Comment by LeaveMyYard** [comment]
@yonahd you are correct, and I think I fixed it a few days ago. Currently error with kubeconfig will only be shown in a runtime.

**Comment by LeaveMyYard** [comment]
I managed to reproduce your issue with empty `current-context` and added a fix for that. Please confirm that.

**Comment by LeaveMyYard** [comment]
Feel free to reopen if the fix did not help

**Comment by marafa-sugarcrm** [comment]
i do not set current context. that is correct . i always use `--context` to avoid barfing the wrong cluster
