### ISSUE TITLE
KRR computes recommendation for lots of Kubernetes objects, but if just one errors out no results are printed

### ISSUE THREAD

**Issue by matheuscscp** [robusta-dev/krr#301]
**Describe the bug**
KRR computes recommendations for lots of Kubernetes objects but if just one errors out, no useful results are printed.

**To Reproduce**
1. Have an unstable Prometheus cluster
2. Run `krr simple`
3. Observe that even though lots of `INFO     Calculated recommendations for ...` lines are printed, if one object errors out, none of these recommendations are printed, only the error/traceback is printed.

**Expected behavior**
A partial result is printed with the recommendations of the objects for which KRR was able to compute, and a list of errors for the objects that had errors.

**Are you interested in contributing a fix for this?**
Yes!!

**Desktop (please complete the following information):**
 - OS: MacBook-Pro 23.3.0 Darwin Kernel Version 23.3.0: Wed Dec 20 21:30:59 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T6030 arm64
 - Version: v1.10.0

**Comment by aantn** [comment]
Strongly in favor of a fix! It would be best to do it on top of the prometheus-workload-loader branch as that has some major changes that will be merged soon. 

We would love to receive a PR for this.

**Comment by aantn** [comment]
Hey, I had an easy test case for this so I fixed it myself. Please test and confirm that this works.

**Comment by aantn** [comment]
Note that the fix isn't merged yet - it is on #307
