### ISSUE TITLE
[v1.12.0-main] - ERROR - CERTIFICATE_VERIFY_FAILED certificate trying Recommendations

### ISSUE THREAD

**Issue by jrosal06** [robusta-dev/krr#319]
Hello team,

we have this issue when we try to run KRR on my OpenShift cluster

          WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate  connectionpool.py:826 verify failed: self signed certificate in certificate chain (_ssl.c:1129)'))': /apis/autoscaling/v2/horizontalpodautoscalers?watch=False WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate  connectionpool.py:826 verify failed: self signed certificate in certificate chain (_ssl.c:1129)'))': /apis/autoscaling/v2/horizontalpodautoscalers?watch=False WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate  connectionpool.py:826 verify failed: self signed certificate in certificate chain (_ssl.c:1129)'))': /apis/autoscaling/v2/horizontalpodautoscalers?watch=False ERROR    Error trying to list hpa in cluster infraco-uat/api-ocp4-htr-cloudteco-com-ar:6443/kube:admin: HTTPSConnectionPool(host='api.ocp4-htr.cloudteco.com.ar', port=6443): Max retries exceeded with url:  __init__.py:456 /apis/autoscaling/v2/horizontalpodautoscalers?watch=False (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))

We need your support to resolve this issue. Thanks

**Comment by aantn** [comment]
We are tracking this at https://github.com/robusta-dev/homebrew-krr/issues/5 and will hopefully have a fix soon!

**Comment by aantn** [comment]
@arikalon1 can we close?

**Comment by aantn** [comment]
(and if so, lets close https://github.com/robusta-dev/homebrew-krr/issues/5 too)

**Comment by arikalon1** [comment]
closing it
