### ISSUE TITLE
HTTP Status Code 400

### ISSUE THREAD

**Issue by ampc** [robusta-dev/krr#325]
**Describe the bug**
The output returns the values and suggestions but it displays an error in the beginning.

**To Reproduce**
1. Execute the following
krr simple  --allow-hpa --prometheus-url http://mimir.prd.monitoring.xyz/prometheus/ --prometheus-headers 'X-Scope-OrgID:runtime-metrics' --prometheus-auth-header 'Basic xyz' --prometheus-label cluster  --prometheus-cluster-label rtmc-02 -v

**Expected behavior**
Do not return errors

**Screenshots**
<img width="1795" alt="image" src="https://github.com/user-attachments/assets/20cf422d-ac7d-4b02-aee6-da4b5e69352b">

**Are you interested in contributing a fix for this?**
Yes

**Desktop (please complete the following information):**
 - OS: mac OS
 - Version v1.13.0

**Additional context**
Using Mimir with multi tenancy

**Comment by aantn** [comment]
Does this happen on the `prometheus-workload-loader` branch as well?
