### ISSUE TITLE
Prometheus auth header set as Basic does not work

### ISSUE THREAD

**Issue by Ezzahhh** [robusta-dev/krr#335]
**Describe the bug**

**To Reproduce**
1. Place Prometheus or Mimir behind Basic Auth (like cortex/mimir nginx configuration)
2. `krr simple -p https://mimir.your_company.com/prometheus --prometheus-auth-header 'Basic test:base64encoded'`

If I curl like `curl -XPOST https://mimir.your_company.com/prometheus --user test:not-base64` then it works fine so it is unlikely user error.

**Expected behavior**
1. Basic authorization header should be passed and not 401 unauthorized

**Are you interested in contributing a fix for this?**
Yes but unsure from initial peruse of the code I don't see why this doesn't work. Perhaps related to using the underlying `prometrix` library.

**Comment by Ezzahhh** [comment]
This was an error on my part. Ensure to do: `echo -n "username:password" | base64` to ensure no extra line

**Comment by aantn** [comment]
Cool, thanks for the update :)
