### ISSUE TITLE
Enquiry with calculate logic and parameter

### ISSUE THREAD

**Issue by Wyifei** [robusta-dev/krr#384]
1. --timeframe-duration

What does this parameter represent? Does it mean the same thing as Prometheus' scrape_interval?

2. --points-required

What does "points" refer to in this context?

3. Calculation logic
If a deployment performs a rollout restart and creates a new ReplicaSet, will KRR generate recommendations based on both the old and new ReplicaSets?

**Comment by aantn** [comment]
> What does this parameter represent? Does it mean the same thing as Prometheus' scrape_interval?
No, scrape_interval is how often you scrape. This is equivalent to step, which is explained here - https://www.robustperception.io/step-and-query_range/

> What does "points" refer to in this context?
How many data points need to come back from the Prometheus queries (this is effected by step - see above)

> If a deployment performs a rollout restart and creates a new ReplicaSet, will KRR generate recommendations based on both the old and new ReplicaSets?
Correct. If for some reasons this isn't possible, you'll see a warning in the logs.
