### ISSUE TITLE
Connecting to prometheus Behaviour 

### ISSUE THREAD

**Issue by yonahd** [robusta-dev/krr#4]
In the documentation, it should be made clear that the Prometheus needs to have one of the above labels
```
"app=kube-prometheus-stack-prometheus",
"app=prometheus,component=server",
"app=prometheus-server",
"app=prometheus-operator-prometheus",
"app=prometheus-msteams",
"app=rancher-monitoring-prometheus",
"app=prometheus-prometheus",
```

In addition, IMO the Ingress host should likely be the default URL.
As a fallback, it can try to look for the Service LB or access the Prometheus through the cluster API

Another small point as developers may not have access to the prometheus server namespace, it might be worth saying the recommended way to run this is using the `-p` flag

**Comment by aantn** [comment]
Hi @yonahd, thanks for reporting.

What do you mean about the Ingress host? Can you share an example?

@pablos44 can you add a section to the readme about how Prometheus is discovered?

**Comment by yonahd** [comment]
Hi @aantn 
I did not see it looking for an ingress host which I think should be chosen as a first option.
See the diagram below
![Flowchart](https://user-images.githubusercontent.com/47282577/232800180-9c5f0f2c-3912-4f7f-92e1-881351b4ff53.jpg)

**Comment by Sam-Sundar** [comment]
Hey Guys,


I'm facing below error while running the python script

```bash
[DEBUG] Initializing PrometheusLoader for xx-xx-xx-xx cluster          
(/Users/sam/xx/Tasks/Repos/devops/kubernetes/krr/robusta_krr/core/integrations/prometheus.py:65)
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /Users/sam/xx/Tasks/Repos/devops/kubernetes/krr/robusta_krr/core/integrations/prometheus. │
│ py:102 in _check_prometheus_connection                                                           │
│                                                                                                  │
│    99 │   │   │   │   # This query should return empty results, but is correct                   │
│   100 │   │   │   │   params={"query": "example"},                                               │
│   101 │   │   │   )                                                                              │
│ ❱ 102 │   │   │   response.raise_for_status()                                                    │
│   103 │   │   except (ConnectionError, HTTPError) as e:                                          │
│   104 │   │   │   raise PrometheusNotFound(                                                      │
│   105 │   │   │   │   f"Couldn't connect to Prometheus found under {self.prometheus.url}\nCaus   │
│                                                                                                  │
│ /opt/homebrew/lib/python3.10/site-packages/requests/models.py:1021 in raise_for_status           │
│                                                                                                  │
│   1018 │   │   │   )                                                                             │
│   1019 │   │                                                                                     │
│   1020 │   │   if http_error_msg:                                                                │
│ ❱ 1021 │   │   │   raise HTTPError(http_error_msg, response=self)                                │
│   1022 │                                                                                         │
│   1023 │   def close(self):                                                                      │
│   1024 │   │   """Releases the connection back to the pool. Once this method has been            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
HTTPError: 503 Server Error: Service Unavailable for url: https://xx.xx.xx.xx/api/v1/namespaces/monitoring/services/prometheus-kube-prometheus-prometheus:9090/proxy/api/v1/query?query=example

The above exception was the direct cause of the following exception:
```

**Comment by yonahd** [comment]
@Sam-Sundar how is your prometheus exposed?

**Comment by Sam-Sundar** [comment]
Hey @yonahd,

ClusterIP. Below is my Prometheus Service details. 
```yaml
➜  krr git:(main) kubectl get svc
NAME                                          TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)                      AGE
alertmanager-operated                         ClusterIP   None           <none>        9093/TCP,9094/TCP,9094/UDP   108d
prometheus-grafana                            ClusterIP   10.64.4.36     <none>        80/TCP                       108d
prometheus-kube-prometheus-alertmanager       ClusterIP   10.64.1.120    <none>        9093/TCP                     108d
prometheus-kube-prometheus-operator           ClusterIP   10.64.12.215   <none>        443/TCP                      108d
prometheus-kube-prometheus-prometheus         ClusterIP   10.64.10.185   <none>        9090/TCP                     108d
prometheus-kube-prometheus-thanos-discovery   ClusterIP   None           <none>        10901/TCP,10902/TCP          108d
prometheus-kube-state-metrics                 ClusterIP   10.64.12.193   <none>        8080/TCP                     108d
prometheus-operated                           ClusterIP   None           <none>        9090/TCP,10901/TCP           108d
prometheus-prometheus-node-exporter           ClusterIP   10.64.12.253   <none>        9100/TCP                     108d
thanos-compactor                              ClusterIP   10.64.15.177   <none>        10902/TCP                    108d
thanos-query                                  ClusterIP   10.64.14.30    <none>        9090/TCP                     108d
thanos-store                                  ClusterIP   None           <none>        10901/TCP,10902/TCP          108d
```

**Comment by yonahd** [comment]
Is there any ingress or any way to access to it externally?

**Comment by Sam-Sundar** [comment]
For Promtheus, nope. We have for Grafana alone. I can change the configuration to expose thro' NodePort ?

**Comment by yonahd** [comment]
@aantn @LeaveMyYard is there any way krr can access the prometheus?

**Comment by yonahd** [comment]
You can use port forwarding and provide the -p flag

**Comment by Sam-Sundar** [comment]
Thanks a lot @yonahd

**Comment by LeaveMyYard** [comment]
@yonahd @Sam-Sundar That's correct, port-forwarding is a good option in this case
I will add this to readme for future users

**Comment by yonahd** [comment]
@LeaveMyYard will there be support for discovering the ingress host?

**Comment by LeaveMyYard** [comment]
@yonahd Can you explain in details how do you propose to search for an Ingress? What do you think should be an algorithm to find the ingress with prometheus?

**Comment by yonahd** [comment]
@LeaveMyYard Created a small PR to add this behavior
https://github.com/robusta-dev/krr/pull/16

**Comment by Sam-Sundar** [comment]
> @yonahd @Sam-Sundar That's correct, port-forwarding is a good option in this case I will add this to readme for future users

Hey @yonahd,

I've edited the readme for `-p` flag. PR for the same [#17](https://github.com/robusta-dev/krr/pull/17)

**Comment by yonahd** [comment]
@Sam-Sundar the mainteners added
https://github.com/robusta-dev/krr#example-of-using-port-forward-for-prometheus

**Comment by aantn** [comment]
@yonahd thanks for the PR.

Can you explain a little more the need? You're searching for the same labels, right? So the discovery will succeed/fail in the same scenarios as before.

What's the advantage of going through the ingress and not the service?

**Comment by yonahd** [comment]
@aantn sorry for the confusion.

There are 2 separate issues I raised here.
1. The documentation of how prometheus is discovered (e.g. the labels)
2. The fact that krr tries discovering the prometheus service loadbalancer and not the ingress which is the more common way to expose it AFAIK. 

My PR is regarding the second point.

**Comment by LeaveMyYard** [comment]
@yonahd 

Opened #21 for additional info on autodiscovery in readme. WDYT?

**Comment by LeaveMyYard** [comment]
As #16 was merged, I am closing this MR af finished
