### ISSUE TITLE
PrometheusNotFound: when running the Rescan from the UI.

### ISSUE THREAD

**Issue by mmulligan03** [robusta-dev/krr#43]
**Describe the bug**

In the UI under Efficiency when you select cluster to rescan and then click Rescan you get an error in the logs that says `PrometheusNotFound: Prometheus url could not be found while scanning in default cluster`
 
I am using an external prometheus

**To Reproduce**
1. Go to 'Efficiency`
2. Select a cluster from the `Cluster to rescan` dropdown.
3. Click on Rescan'
4. Wait for message to popup saying the job failed.
5. See error in logs 

**Expected behavior**
I would expect this to rescan the cluster

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 113.0.5672.92

**Comment by LeaveMyYard** [comment]
Hey, @mmulligan03 

What prometheus installation do you have on your cluster? Does it work with robusta itself?

**Comment by LeaveMyYard** [comment]
Closing this issue because no answer received

And it actually refers to an old Robusta UI, not a KRR itself
