### ISSUE TITLE
Restrict workload selection

### ISSUE THREAD

**Issue by dohnto-s1** [robusta-dev/krr#62]
**Is your feature request related to a problem? Please describe.**
One might have a huge cluster and want to focus on optimizing just a particular workload.
Prometheus queries while analysing all worklaods in a cluster/namespace might take too long otherwise.

**Describe the solution you'd like**
Introduce a new command line argument as kubectl has:

```
    -l, --selector='':
	Selector (label query) to filter on, supports '=', '==', and '!='.(e.g. -l key1=value1,key2=value2). Matching
	objects must satisfy all of the specified label constraints.
```

to limit the workload selection. E. g:
```
krr simple --context my-cluster --namespace kube-system --selector app-instance=metrics-server
# or
krr simple --context my-cluster --namespace kube-system --selector owner=devops
```

**Describe alternatives you've considered**

```
krr simple --context my-cluster --namespace kube-system --workload Deployment/metrics-server
```

**Additional context**

Thanks for this wonderful tool. Happy to learn if there is alternative solution for me.

**Comment by dohnto-s1** [comment]
Now I hit an issue when Prometheus is unable to give me the results and the request fails with 431. I don't understand the details `krr`, but would implementation of feature above help as well? 

> PrometheusApiClientException: HTTP Status Code 431 (b'431 Request Header Fields Too Large')

**Comment by arikalon1** [comment]
Thanks for reporting it @dohnto-s1 

I think this issue is similar to #60 

Does limiting `krr` to a specific namespace using `krr simple -n default` can be a workaround until we fix it?

**Comment by dohnto-s1** [comment]
This unfortunately happens when running with `-n`.

**Comment by LeaveMyYard** [comment]
And I really like your proposal for selector flag, we should 100% implement it

**Comment by dohnto-s1** [comment]
@LeaveMyYard Looks awesome, thanks!
