### ISSUE TITLE
Add support to Grafana cloud

### ISSUE THREAD

**Issue by Pavaningithub** [robusta-dev/krr#63]
**Is your feature request related to a problem? Please describe.**
We scrape the metrics using Grafana agent which sends data to Grafana cloud.

**Describe the solution you'd like**
It would be great if you could allow passing Grafana cloud Prometheus query endpoint with username and password.
something like below
```bash
krr -p https://prometheus-xxx.grafana.net/api/prom -u <username> -p <password>
```

**Comment by LeaveMyYard** [comment]
Hey, @Pavaningithub !

Sorry for long waiting, just got time to investigate Grafana cloud 

I think Grafana cloud actually should work with `--prometheus-auth-header` command. You should be able to use `Bearer <API key>` or `Basic <user:password in base64>` to authorize.

If someone can approve it - I will close the issue. If not - I will try to verify myself

**Comment by LeaveMyYard** [comment]
Closing. See the above message for a solution

**Comment by aantn** [comment]
@pavangudiwada can you add documentation for this to the README?

**Comment by serdarkkts** [comment]
@aantn @pavangudiwada I have been using `krr` with Grafana Cloud lately, and it works like a charm. I added the instructions to make `krr` work with Grafana Cloud on this [MR](https://github.com/robusta-dev/krr/pull/144). Hopefully, it can make it easier for Grafana Cloud and `krr` users.
