### ISSUE TITLE
Add support for rollouts

### ISSUE THREAD

**Issue by arnoldyahad** [robusta-dev/krr#65]
Hey everyone,
We are mostly using argocd rollout resource instead of deployments:
```
apiVersion: argoproj.io/v1alpha1
kind: Rollout
```
The `Rollout` of ArgoCD is a popular CRD that is used by most of the people that use ArgoCD, its basically a deployment but with extra capabilities.

It would be great if the `krr` tool could support it so it will show results of Rollouts as well.

**Comment by LeaveMyYard** [comment]
Good Idea! Thanks, @arnoldyahad 

We do not yet support ReplicaSets, that are not bound to Deployment/StatefullSet, so this is good one to also implement

**Comment by arnoldyahad** [comment]
@LeaveMyYard I had the time to work on a solution: https://github.com/robusta-dev/krr/pull/85

**Comment by LeaveMyYard** [comment]
Closing as PR was merged
