### ISSUE TITLE
Error trying to list pods

### ISSUE THREAD

**Issue by im-alfa** [robusta-dev/krr#77]
**Describe the bug**
When I run the simplest possible command, no pod is detected.

Full output with -v arg: https://pastebin.com/XZTGz2HY

**Screenshots**
![image](https://github.com/robusta-dev/krr/assets/25107205/b25c4629-7de2-4be2-b886-5fbb94cb74e5)

**Desktop (please complete the following information):**
 - OS: Ubuntu WSL
 

**Additional context**
- K8s version: 1.26.4

**Comment by LeaveMyYard** [comment]
Hello, @im-alfa !
Thanks for creating an issue!

Can you tell me what kubernetes provider do you have?
Also, if you have brew available, it would help if you try using KRR from brew

**Comment by im-alfa** [comment]
Hi @LeaveMyYard,

Managed OVH Kubernetes ([https://www.ovhcloud.com/en-ie/public-cloud/kubernetes/](https://www.ovhcloud.com/en-ie/public-cloud/kubernetes/))

I don't have any MacOS computers out there, but I have a friend who does. I'll ask him.

**Comment by LeaveMyYard** [comment]
Hey again, @im-alfa 
Can you try running with this branch? https://github.com/robusta-dev/krr/tree/pod-list-operator-bug

**Comment by im-alfa** [comment]
Hi @LeaveMyYard,

Sorry for the delay. It's fully working now.

Thank you so much!
