### ISSUE TITLE
Brew package

### ISSUE THREAD

**Issue by 0dragosh** [robusta-dev/krr#8]
Right now installing is a little convoluted if you just want to take the tool for a spin, we are all familiar with the pain of python envs.

It would be great if krr had a brew package.

**Comment by LeaveMyYard** [comment]
Hey, @0dragosh!

Brew/snap/apt are in the nearest plans, should be coming really soon.
I will update you in this issue as soon as it will be available

**Comment by mortenlj** [comment]
If you package it up so it is installable using normal python tools and put it on pypi, [pipx](https://pypa.github.io/pipx/) is a quick way to get python cli applications installed in their own environment. Would work everywhere you have python, and could be a quicker way to solve the installation problem for all platforms in one go.

**Comment by 0dragosh** [comment]
> If you package it up so it is installable using normal python tools and put it on pypi, [pipx](https://pypa.github.io/pipx/) is a quick way to get python cli applications installed in their own environment. Would work everywhere you have python, and could be a quicker way to solve the installation problem for all platforms in one go.

Brew is fairly standard and straight forward, as well as accessible to a lot of people that use Macs to administer k8s.
It's a nice solution as an alternative to `pip install` but I for one see brew as less hassle and I'm more likely to try out the tool, just my 2c.

**Comment by LeaveMyYard** [comment]
Now application is available to install using `brew` 🎉
