### ISSUE TITLE
Prometheus high memory utilization because of krr queries

### ISSUE THREAD

**Issue by macmiranda** [robusta-dev/krr#83]
**Describe the bug**

I first noticed a problem when I clicked _Rescan_ on the _Efficiency panel_ of [Robusta.dev](http://platform.robusta.dev/) that connects to Prometheus and gathers metrics from my cluster where I have installed the Robusta Helm chart.

My prometheus Pod that normally uses less than 1.5 GiB of memory suddenly needs a lot more than 2.5 GiB. Because it’s running on a node with only 4 GiB ram (and is limited to 3GiB in the Pod spec), the pod is OOM-killed. You can see that behavior in the graph below. Robusta UI also shows the OOM-killed pod.

I believe that feature uses `krr` in the background, so I also tried running it directly on the CLI pointing at the same Prometheus endpoint, which produced the same result.

Anything I could do to improve that (besides the obvious increase in memory limits)?

**To Reproduce**
1. Run `krr` pointing to a Prometheus pod with a 3 GiB memory limit
2. Prometheus should have 250k+ time series and 10k+ label pairs
3. Do not limit the namespaces scanned by `krr`

**Expected behavior**
Not cause Prometheus to crash

**Screenshots**
![image (6)](https://github.com/robusta-dev/krr/assets/17923899/6fa9e29e-4430-41e5-af79-3498b044757c)

**Additional context**

When scanning a single namespace Prometheus doesn't crash but you can still notice a big hike in memory utilization
![image (7)](https://github.com/robusta-dev/krr/assets/17923899/46fb4bc5-b0e2-4037-a7dc-cdb232b5246a)

**Comment by LeaveMyYard** [comment]
It seems like it is related to the amount of parallel queries being really high
We are doing the fix currently, I will update here on the progress

**Comment by Avi-Robusta** [comment]
Just wanted to update there is a pr open that might fix this issue
https://github.com/robusta-dev/krr/pull/82

**Comment by macmiranda** [comment]
So I did some testing with different number of workers. For our setup, it seems 3 workers is the ideal number as you can see in the graph below (and considering that W=3 runs 50% faster than W=1 but only 15% slower than W=6)

![krr_workers_prometheus](https://github.com/robusta-dev/krr/assets/17923899/f3711fa0-c944-493b-9cb8-545c1308d5cf)

Prometheus didn't crash anymore but that's because we doubled the node instance size from 4GiB to 8GiB.

In general, I would say, without looking at the source code, if you need to send such heavy queries to Prometheus, you should probably try to use [precomputed time series](https://prometheus.io/docs/prometheus/latest/configuration/recording_rules/#recording-rules) as much as possible.

**Comment by macmiranda** [comment]
Hi @LeaveMyYard,

Thanks for the work you put into this. I have tested `krr` from the `main` branch and the results are promising.

![image](https://github.com/robusta-dev/krr/assets/17923899/1a12beb4-e9b8-46ba-be89-f3598eb9d286)
(it ran for all namespaces with `-w 1` in about 3 minutes)

As you can see there is still a peak memory utilization when `krr` runs but it seems manageable now.

I'm eager to test it running as a Job in the cluster. Do you know when the next Robusta release will happen? (I'm asking because the next release will contain a fix that limits the memory consumption of the `krr` Job as well).
