### ISSUE TITLE
Add Grafana Mimir integration

### ISSUE THREAD

**Issue by jkrzemin** [robusta-dev/krr#84]
**Is your feature request related to a problem? Please describe.**
Grafana Mimir (even without authentication, so this is partially related to https://github.com/robusta-dev/krr/issues/18) requires specifying the tenant via HTTP header `X-Scope-OrgID`.

**Describe the solution you'd like**
Option to either pass arbitrary headers or specific flag for Mimir.

**Describe alternatives you've considered**

**Additional context**

**Comment by LeaveMyYard** [comment]
Hey, @jkrzemin 

Custom headers is a good idea. We will consider that option.

Do you think `X-Scope-OrgID` is the only thing that is required for the integration with Mimir?

**Comment by jkrzemin** [comment]
Nothing specific to Mimir - they try to keep being as compatible with Prometheus API as possible.

Of course, other stuff for Prometheus applies such as basic auth or Bearer token.
