### ISSUE TITLE
Can't krr use the nodeport port?

### ISSUE THREAD

**Issue by llody55** [robusta-dev/krr#90]
My kubernetes cluster is on another host, and it seems impossible to use nodeport to access the Prometheus server address. What should I do?

![image](https://github.com/robusta-dev/krr/assets/9710645/1c44f692-2640-4696-82bf-ad063c0cf7f4)

**Comment by LeaveMyYard** [comment]
Hey, @llody55

Can you run share logs with `-v` flag added?

**Comment by llody55** [comment]
@LeaveMyYard 
![image](https://github.com/robusta-dev/krr/assets/9710645/4e2c6fe3-8de3-440b-800c-96c0f0d9c943)

**Comment by LeaveMyYard** [comment]
No, I mean the verbosity flag:

```bash
python3 krr.py simple -k /root/.kube/config -p http://192.168.1.227:32456 -v
```

**Comment by LeaveMyYard** [comment]
@llody55 it looks like the issue is not in a prometheus but an issue that was found in https://github.com/robusta-dev/krr/issues/91 related to HPAv2 not available
I will open a PR soon on that
